"""Position-state reconstruction engine (CAS-13/CAS-47).

Replays Aave v2 core events (Deposit/Borrow/Repay/Withdraw) and
LiquidationCall events into per-account, per-reserve collateral/debt
balances queryable at any block — the backbone the state engine needs for bad-
debt severity, the liquidation-wall feature (CAS-51), and the contagion
graph's whale-position nodes (CAS-23).

Known limitations (see also reserves.py / prices.py / interest_index.py
docstrings):
  - Balances now include aToken/debt-token interest accrual (CAS-28 Track
    E, below) -- they are no longer a pure raw-token-unit replay. An earlier
    measurement (against the 5 golden-episode windows only, and
    window-start-relative rather than per-account) found this effect under
    1% and concluded it couldn't explain the mismatch -- **that measurement
    was wrong in a load-bearing way**: after CAS-28 Track D gave
    `InterestIndexOracle` continuous coverage, re-measuring against each
    liquidated account's *actual* last-`Borrow`-to-trigger span (mean ~541
    days held, not a few weeks inside a pulled window) found real
    `variableBorrowIndex` growth averaging 18.4% (median 3.7%, max 627%
    across 32,941 measurements) -- see
    `scripts/analysis/estimate_interest_accrual_gap.py`. Applying it (Track
    E) confirmed the effect is real and load-bearing: see the Track E
    section below for the T2 result. Price staleness (DefiLlama daily vs
    block-level Chainlink) was the next-suspected cause after the original
    (mis-measured) accrual estimate, but
    `scripts/analysis/compare_price_oracle_hf_mismatch.py` (CAS-17, run
    against real Chainlink data + `prices.ChainlinkPriceOracle`) measured
    only a modest effect: on 355 real liquidations with full price coverage
    from both oracles, the mismatch rate drops from 26.5% (DefiLlama) to
    24.2% (Chainlink) -- ~2.3 points, not the dominant driver either.
    Chainlink reserve coverage is still partial (32/37 reserves, see
    `chainlink_feeds.UNCOVERED_RESERVES`); full historical Chainlink data
    beyond the 5 golden-episode windows remains blocked on exhausted Dune
    credits (resets 2026-08-03) -- unlike the accrual data, which Track D
    routed around Dune entirely via Etherscan.
  - Liquidations are applied as a direct debit against the liquidated
    user's collateral/debt (the liquidator's own balance is not credited —
    out of scope for the borrower-side HF this engine exists to recompute).

CAS-28 finding (see `scripts/onchain/fix_gateway_onbehalfof.py`): Aave v2's
`Deposit`/`Borrow` events carry both `user` (msg.sender, the caller) and
`onBehalfOf` (the actual position holder) -- `scripts/dune/aave_v2_core_events.sql`
captured `user`, so gateway/adapter-routed events (WETHGateway,
WrappedTokenGatewayV2, ParaSwap/Uniswap collateral-swap adapters -- ~21.7%
of all Deposit+Borrow volume) were misattributed to the periphery
contract's own ledger bucket instead of the real account. `load_events`
applies a corrections table (regenerated by that script) to re-attribute
`Borrow` unconditionally, and `Deposit` together with the symmetric
`Withdraw` correction below.

  - `Borrow`'s real counterpart, `Repay`, is unaffected by gateway routing
    (its `user` topic is already `onBehalfOf` on-chain, confirmed for both
    direct and gateway-routed calls) -- so correcting `Borrow` alone is
    safe: it can only ever *add* previously-invisible debt to the real
    account, which can only lower a reconstructed HF, never raise one.
    Verified empirically: applying it moves the T2 mismatch rate from
    28.5% to 28.1% (n_measurable +1286, n_mismatch +276 -- all 276 land in
    the newly-measurable population, none of the previously-measurable
    22,561 flip from match to mismatch, which matches the math). Only
    ~11% of the baseline "unexplained" mismatch population (114/1051
    users) even has a corrected `Borrow` in its history, so this alone
    doesn't close the gate -- ruling out gateway misattribution as *the*
    dominant cause, same conclusion as the earlier interest-accrual and
    price-staleness investigations.
  - `Deposit`'s counterpart, `Withdraw`, is NOT symmetric: a gateway
    withdrawal (e.g. `WETHGateway.withdrawETH`) pulls the user's aTokens
    via `transferFrom` *before* calling `LendingPool.withdraw`, so
    `Withdraw`'s `user` topic still resolves to the gateway, not the real
    account -- and `Withdraw` has no `onBehalfOf`-equivalent field to
    decode a fix from directly. `scripts/onchain/fix_gateway_withdraw.py`
    closes this by correlating each gateway-attributed `Withdraw` with the
    aToken `Transfer` that funded it in the same tx (99% coverage of the
    123,981 candidate `Withdraw` events, cross-checked by requiring the
    transfer's amount to exactly equal the `Withdraw`'s). Applying `Deposit`
    without this symmetric fix creates phantom collateral and was confirmed
    to regress the mismatch rate to 73%; `_apply_onbehalfof_correction`
    therefore only reattributes `Deposit` when
    `_WITHDRAW_CORRECTIONS_PATH` also exists.

  **With both fixes applied together, the T2 mismatch rate moves from
  28.1% to 69.2% -- a large regression in the metric, not an improvement.**
  This is not a bug in the correction logic (traced a specific flipped
  liquidation end-to-end against raw on-chain data: the real user's 5 WETH
  deposit was genuinely misattributed to gateway `0xdcd33426...`, and
  correctly re-attributing it, net of that same liquidation's own
  collateral seizure, leaves the account looking healthy -- HF >= 1 -- by
  this engine's current price/threshold assumptions) or in the Withdraw
  correlation's precision (the amount-exactness cross-check independently
  dropped coverage from 123,881 to 122,155 matched rows but only moved the
  mismatch rate from 69.1% to 69.2%, i.e. false-positive correlations were
  not the driver). Instead, ~9,844 liquidations that "matched" under the
  old, misattributed ledger did so *because* the gateway's own aggregate
  bucket was artificially collateral-poor (deposits routed elsewhere),
  making them trivially liquidatable in reconstruction regardless of the
  real account's true, healthier state -- correcting the attribution
  removes that coincidental agreement and re-exposes those accounts to
  whatever the *actual* remaining gap is (mismatch cause breakdown moved
  overwhelmingly into `unexplained` (2,836 -> 8,657) and
  `unexplained_no_chainlink_coverage` (3,056 -> 6,488), not into a new
  artifact bucket). The takeaway: the previous 28.1% figure was partly an
  artifact of this same misattribution bug masking failures, not a
  measure of how close the engine is to the 2% bar -- the true gap is
  larger, and gateway misattribution is fully ruled out as a mismatch
  *reducer* (see CAS-28 ticket notes for the next-step triage among this
  engine's remaining stated simplifications).

Track B (CAS-28, 2026-07-19 next-steps plan): the leading candidate for the
resulting `unexplained` bucket (8,657 events, Chainlink-confirmed HF>=1 at
trigger) was that every `Deposit` had been treated as collateral-eligible
unconditionally, ignoring Aave v2's per-reserve `setUserUseReserveAsCollateral`
toggle -- overcounting collateral would make reconstructed HF look healthier
than reality, exactly this symptom. `scripts/onchain/backfill_collateral_toggle.py`
pulls the `ReserveUsedAsCollateralEnabled`/`Disabled` events that carry this
state and writes a per-(user, reserve) correction table. Unlike the
onBehalfOf/Withdraw corrections above (which re-attribute *who* an event
belongs to, applied once at `load_events` time), collateral eligibility is a
live status that changes independently of ledger deltas -- so it's joined at
*query* time (`positions_at`/`positions_at_many`, via `_collateral_toggle`)
as a `collateral_enabled` column, and only consumed by
`health_factor.compute_health_factor`'s collateral-weighting step, not by the
ledger itself (a disabled reserve is still a real token balance, just not
HF-eligible). Defaults to `True` (the prior behavior) wherever the
corrections table is missing or has no toggle event yet for a (user,
reserve) pair, so this is a no-op for callers that haven't pulled it.

Track C (CAS-28): Track B didn't move the `unexplained` bucket (8,657 ->
8,696, essentially flat). Hand-verifying a stratified 28-liquidation sample
of that bucket directly against Etherscan (the ticket's fallback plan) found
the real cause instead: this engine only replays `LendingPool` events, but
Aave v2's aTokens are themselves ordinary transferable ERC20s, and several of
Aave's own periphery adapters (`UniswapRepayAdapter`,
`UniswapLiquiditySwapAdapter`, `ParaSwapLiquiditySwapAdapter`) execute a
repay-with-collateral or collateral-swap by pulling a user's aTokens directly
via `transferFrom` against the aToken contract, never calling
`LendingPool.withdraw` -- collateral that genuinely left the account stays
counted here, understating risk. 19/28 (68%) of the sample had at least one
such "naked" (non-mint/burn) aToken transfer before their liquidation
trigger. `scripts/onchain/backfill_atoken_transfers.py` pulls every aToken's
`Transfer` log Aave-wide (37 reserves) and writes a corrections table; unlike
Track B this is a genuine balance delta (not a live status), so
`PositionStateEngine.__post_init__` concatenates it onto the ledger
`build_ledger` already produced, rather than joining it at query time.
(`_atoken_transfer_ledger_rows` is deliberately *not* called from inside
`build_ledger` itself, which stays a pure function of its `events`/
`reserve_table` arguments for testability -- this correction table is
global/protocol-wide and independent of whatever `events` a caller passes
in.)

One wrinkle: when a liquidator opts to `receiveAToken`, Aave v2 seizes
collateral via this exact same transfer mechanism inside the
`LiquidationCall` transaction itself -- `build_ledger`'s `LiquidationCall`
handling already accounts for that seizure, so applying the transfer *again*
would double-debit the borrower for their own liquidation (confirmed on the
sample: 12/54 naked transfers shared a tx_hash with their own trigger
liquidation). `_atoken_transfer_ledger_rows` excludes any transfer whose
`tx_hash` also carries a `LiquidationCall` in `events` to avoid this.

**Result: applying Track C moves the T2 mismatch rate from 68.2% (Track B) to
53.9%** -- a genuine 14.3-point improvement, unlike Track B's near-zero
effect, confirming the aToken-transfer hypothesis is real and load-bearing.
`unexplained` drops from 8,696 to 7,160 and `unexplained_no_chainlink_coverage`
from 6,534 to 4,724. Still far short of the 2% gate -- the T2 gate remains
FAILING and more root-causing is needed among the remaining mismatches (see
CAS-28 ticket notes for next steps).

Track D (CAS-28): sizing the residual `unexplained` bucket found it's a
close-margin, systematic gap (median HF 1.31, 72.4% within HF<=1.5), not a
few wild outliers -- pointing back at interest-index accrual (see the
"Known limitations" section above), which the original estimate had
mis-measured as negligible because it only covered 5 disjoint golden-episode
windows and measured growth from each window's *start*, not from the
account's actual `Borrow`. `scripts/onchain/backfill_reserve_index.py` pulls
`ReserveDataUpdated` for the full [11.5M, 24.5M] block range via Etherscan
(free, unlike the Dune-metered original), giving `InterestIndexOracle`
continuous coverage. Re-measuring against real per-account Borrow-to-trigger
spans (`scripts/analysis/estimate_interest_accrual_gap.py`) found real
`variableBorrowIndex` growth averaging 18.4% (median 3.7%, mean 541 days
held) across 32,941 real (account, reserve, trigger) measurements -- a
plausible, load-bearing, directionally-correct explanation for a meaningful
share of the residual mismatch. Quantifying the effect (this paragraph) was
a prerequisite to, not the same as, actually correcting the ledger for it
-- see Track E, below, for that.

Track E (CAS-28): applies the Track D accrual finding to this engine's
balance replay, using Aave's own on-chain "scaledBalance" pattern rather
than bolting compounding onto the existing raw-delta ledger: each ledger
row's raw delta is divided by the interest index at its own event block
(`_scale_ledger_rows`, giving an index-normalized "scaled" delta), scaled
deltas are cumulatively summed exactly as raw deltas were before, and the
running scaled balance is multiplied back up by the index *at query time*
(`_reinflate` for `positions_at`, inlined in `positions_at_many`) --
collateral scales by the `liquidity` index, debt by `variable_borrow`,
matching which leg Track D found actually drives the effect. Coverage gaps
(no oracle, or a specific reserve/block outside `InterestIndexOracle`'s
range) fall back to a 1.0 multiplier *per row*, not per user -- see
`interest_index.py`'s module docstring for why row-level fallback was
chosen over an all-or-nothing per-user gate.

**Result: applying Track E moves the T2 mismatch rate from 53.9% (Track C)
to 37.8%** -- a genuine 16.1-point improvement, confirming the accrual
hypothesis is real and load-bearing on top of Tracks B/C, not merely
plausible. `unexplained` drops from 7,160 to 6,363 and
`unexplained_no_chainlink_coverage` from 4,724 to 4,189; `n_measurable` also
rises (24,203 -> 31,773) since some previously-net-zero (raw units)
positions now carry a small genuine residual balance once same-nominal-
amount deposit/withdraw pairs are correctly priced at their different
issuance/redemption indices, pulling more of their reserves into price/
threshold coverage. Still far short of the 2% gate -- the T2 gate remains
FAILING and more root-causing is needed among the remaining mismatches (see
CAS-28 ticket notes for next steps).
"""

from __future__ import annotations

import glob
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

from cascadesignal.state import reserves as reserves_module
from cascadesignal.state.health_factor import HealthFactorResult, compute_health_factor
from cascadesignal.state.interest_index import (
    InterestIndexOracle,
    _compounded_interest_array,
)
from cascadesignal.state.prices import PriceOracle

CORE_EVENT_TYPES = frozenset({"Deposit", "Borrow", "Repay", "Withdraw"})
LIQUIDATION_EVENT_TYPES = frozenset({"LiquidationCall"})

_EPS = 1e-9

_LEDGER_COLUMNS = [
    "block_number",
    "log_index",
    "user",
    "reserve",
    "d_collateral",
    "d_debt",
]


def _empty_ledger_rows() -> pd.DataFrame:
    """Correctly-*typed* empty ledger frame (`block_number`/`log_index` as
    int64, `scaled_collateral`/`scaled_debt` as float64) -- a bare
    `pd.DataFrame(columns=[...])` defaults every column to `object` dtype
    with no data to infer from, which breaks `positions_at_many`'s
    `groupby(...).cumsum()` downstream (CAS-28 H3).

    `tx_hash` (CAS-28 H4-general): only ever populated on the H3 exact-ledger
    path (see `_exact_atoken_ledger_rows`/`_exact_variable_debt_ledger_rows`)
    -- needed by `position_at_log_index` to tell "an earlier event in this
    SAME liquidation's own transaction" (must stay excluded from its
    pre-state) apart from "an earlier event in a genuinely different
    transaction" (must be included). The pre-H3 `build_ledger` fallback path
    never sets this column at all; `position_at_log_index` degrades to its
    pre-fix exact-log_index cutoff there, which has no such bug (see that
    function's docstring)."""
    return pd.DataFrame(
        {
            "block_number": pd.Series(dtype="int64"),
            "log_index": pd.Series(dtype="int64"),
            "user": pd.Series(dtype="object"),
            "reserve": pd.Series(dtype="object"),
            "scaled_collateral": pd.Series(dtype="float64"),
            "scaled_debt": pd.Series(dtype="float64"),
            "tx_hash": pd.Series(dtype="object"),
        }
    )


_ONBEHALFOF_CORRECTIONS_PATH = Path(
    "data/raw/corrections/aave_v2_onbehalfof/chain=1/onbehalfof.parquet"
)
_WITHDRAW_CORRECTIONS_PATH = Path(
    "data/raw/corrections/aave_v2_withdraw/chain=1/withdraw.parquet"
)
_COLLATERAL_TOGGLE_CORRECTIONS_PATH = Path(
    "data/raw/corrections/aave_v2_collateral_toggle/chain=1/collateral_toggle.parquet"
)
_ATOKEN_TRANSFER_CORRECTIONS_PATH = Path(
    "data/raw/corrections/aave_v2_atoken_transfer/chain=1/atoken_transfer.parquet"
)
_TOKEN_LEDGER_DIR = Path("data/raw/corrections/aave_v2_token_ledger/chain=1")
_ATOKEN_EVENTS_PATH = _TOKEN_LEDGER_DIR / "atoken_events.parquet"
_VARIABLE_DEBT_EVENTS_PATH = _TOKEN_LEDGER_DIR / "variable_debt_events.parquet"
_STABLE_DEBT_EVENTS_PATH = _TOKEN_LEDGER_DIR / "stable_debt_events.parquet"

_COLLATERAL_TOGGLE_COLUMNS = ["user", "reserve", "block_number", "log_index", "enabled"]
_ATOKEN_TRANSFER_COLUMNS = [
    "block_number",
    "log_index",
    "tx_hash",
    "reserve",
    "from_user",
    "to_user",
    "value_raw",
]
_RAY = 1e27


def _apply_onbehalfof_correction(events: pd.DataFrame) -> pd.DataFrame:
    """Re-attribute `Borrow` rows from `user` (msg.sender) to `onBehalfOf`
    (the real position holder) using the corrections table from
    `scripts/onchain/fix_gateway_onbehalfof.py`. `Borrow` alone is always
    safe (its counterpart `Repay` already resolves correctly on-chain, see
    module docstring) so it's applied unconditionally whenever the
    corrections table exists.

    `Deposit` rows are only re-attributed when
    `_WITHDRAW_CORRECTIONS_PATH` *also* exists: applying the `Deposit`
    correction without the symmetric `Withdraw` correction
    (`_apply_withdraw_correction`, `scripts/onchain/fix_gateway_withdraw.py`)
    creates phantom collateral and regresses the T2 mismatch rate from
    28.1% to 73% (confirmed empirically) -- so a checkout that has the
    `Borrow`/`Deposit` onBehalfOf pull but hasn't run the newer `Withdraw`
    correlation pull falls back to the pre-existing Borrow-only behavior
    instead of silently regressing.

    A no-op (returns `events` unchanged) if the onBehalfOf table hasn't
    been generated at all, so callers without the pull still work, just
    with the pre-fix gateway-misattribution behavior."""
    if not _ONBEHALFOF_CORRECTIONS_PATH.exists():
        return events
    corrections = pd.read_parquet(
        _ONBEHALFOF_CORRECTIONS_PATH,
        columns=["tx_hash", "log_index", "event_type", "onbehalfof"],
    )
    event_types = {"Borrow"}
    if _WITHDRAW_CORRECTIONS_PATH.exists():
        event_types.add("Deposit")
    corrections = corrections[corrections["event_type"].isin(event_types)].drop(
        columns=["event_type"]
    )
    events = events.merge(corrections, on=["tx_hash", "log_index"], how="left")
    mask = events["onbehalfof"].notna()
    events.loc[mask, "user"] = events.loc[mask, "onbehalfof"]
    return events.drop(columns=["onbehalfof"])


def _apply_withdraw_correction(events: pd.DataFrame) -> pd.DataFrame:
    """Re-attribute gateway-routed `Withdraw` rows to their real position
    holder using the aToken `Transfer`-event correlation table from
    `scripts/onchain/fix_gateway_withdraw.py` -- `Withdraw` has no
    `onBehalfOf`-equivalent field to decode a fix from directly (see module
    docstring), so this table is built by correlating each gateway-attributed
    `Withdraw` with the same-tx aToken `Transfer` that funded it. A no-op if
    that table hasn't been generated yet."""
    if not _WITHDRAW_CORRECTIONS_PATH.exists():
        return events
    corrections = pd.read_parquet(
        _WITHDRAW_CORRECTIONS_PATH, columns=["tx_hash", "log_index", "real_user"]
    )
    events = events.merge(corrections, on=["tx_hash", "log_index"], how="left")
    mask = events["real_user"].notna()
    events.loc[mask, "user"] = events.loc[mask, "real_user"]
    return events.drop(columns=["real_user"])


def _load_collateral_toggle_events() -> pd.DataFrame:
    """Per-(user, reserve) collateral-eligibility toggle history from
    `scripts/onchain/backfill_collateral_toggle.py` -- Aave v2's
    `ReserveUsedAsCollateralEnabled`/`Disabled` events (Track B, CAS-28).
    Sorted by (user, reserve, block_number, log_index) so the *last* row
    within a (user, reserve) group is always its most recent state as of any
    later block -- `PositionStateEngine` relies on that invariant when
    looking up the flag at query time. Returns an empty (but correctly
    shaped) frame if the pull hasn't been run yet, so callers are a no-op
    (falls back to the prior "every deposit is collateral-eligible"
    behavior) rather than erroring."""
    if not _COLLATERAL_TOGGLE_CORRECTIONS_PATH.exists():
        return pd.DataFrame(columns=_COLLATERAL_TOGGLE_COLUMNS)
    toggle = pd.read_parquet(_COLLATERAL_TOGGLE_CORRECTIONS_PATH)
    return toggle.sort_values(
        ["user", "reserve", "block_number", "log_index"], kind="mergesort"
    ).reset_index(drop=True)


def _load_atoken_transfer_corrections() -> pd.DataFrame:
    """ "Naked" (non-mint/burn) aToken `Transfer` events from
    `scripts/onchain/backfill_atoken_transfers.py` (Track C, CAS-28) -- each
    row is real collateral movement between two live accounts that no
    `LendingPool` event captures (e.g. Aave's own repay-with-collateral /
    collateral-swap adapters pulling aTokens directly via `transferFrom`).
    Returns an empty (but correctly shaped) frame if the pull hasn't been run
    yet, so callers are a no-op (falls back to the prior "only LendingPool
    events move balances" behavior) rather than erroring."""
    if not _ATOKEN_TRANSFER_CORRECTIONS_PATH.exists():
        return pd.DataFrame(columns=_ATOKEN_TRANSFER_COLUMNS)
    return pd.read_parquet(_ATOKEN_TRANSFER_CORRECTIONS_PATH)


@lru_cache(maxsize=4)
def _load_token_ledger_events_cached(
    atoken_path: str, variable_debt_path: str, stable_debt_path: str
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame] | None:
    paths = (Path(atoken_path), Path(variable_debt_path), Path(stable_debt_path))
    if not all(p.exists() for p in paths):
        return None
    atoken_events, variable_debt_events, stable_debt_events = (
        pd.read_parquet(p) for p in paths
    )
    return atoken_events, variable_debt_events, stable_debt_events


def _load_token_ledger_events() -> (
    tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame] | None
):
    """`(atoken_events, variable_debt_events, stable_debt_events)` from the
    CAS-28 H3 full-history token-event pull
    (`scripts/onchain/backfill_token_ledger_events.py`), or `None` if it
    hasn't been run yet -- same no-op-when-missing convention as every other
    CAS-28 correction, so a checkout without the pull reproduces pre-H3
    behavior (`build_ledger` + Track C + `_scale_ledger_rows`'s nearest-prior
    index lookup) rather than erroring. All three files are written together
    by that script, so presence is checked as all-or-nothing.

    Cached (`_load_token_ledger_events_cached`, keyed on the three path
    *values*, mirroring `_load_interest_index_oracle`): the parquets are
    multi-million-row, expensive enough that re-reading them for every
    `PositionStateEngine` instantiation would badly slow down the test
    suite, which constructs many engines from tiny synthetic fixtures --
    since the H3 path is triggered by file *presence*, not by whatever
    `events` a caller passes in, every one of those would otherwise still
    pay the full real-data read. Keying the cache on the path values (read
    fresh from the module attributes on every call, not baked into the
    cached function itself) keeps this safe under `monkeypatch.setattr` --
    each test's own tmp_path naturally gets its own cache entry instead of
    colliding with another test's or production's."""
    return _load_token_ledger_events_cached(
        str(_ATOKEN_EVENTS_PATH),
        str(_VARIABLE_DEBT_EVENTS_PATH),
        str(_STABLE_DEBT_EVENTS_PATH),
    )


def _exact_atoken_ledger_rows(
    atoken_events: pd.DataFrame, decimals_by_address: dict
) -> pd.DataFrame:
    """Collateral ledger rows built directly from aToken `Mint`/`Burn`/
    `BalanceTransfer` events (CAS-28 H3), with the *exact* per-event index
    embedded in the event itself (`scaled = value / index`) -- no nearest-
    prior lookup, no LendingPool-event replay, no gateway/periphery-adapter
    correction needed: the token's own `from`/`to` fields always name the
    real position holder regardless of which wrapper called it (see module
    docstring). Supersedes `build_ledger`'s collateral rows and
    `_atoken_transfer_ledger_rows` (Track C) wherever this data is present.

    `Mint`'s indexed address is (confusingly, per Aave's own naming) the
    *credited* account; `Burn`'s first indexed address is the *debited*
    account (its second, `target`, is just where the underlying goes, not a
    balance effect) -- both confirmed against each event's companion
    standard `Transfer` in the same tx (see the backfill script's
    docstring)."""
    if atoken_events.empty:
        return _empty_ledger_rows()

    a = atoken_events
    decimals = a["reserve"].map(decimals_by_address).fillna(18)
    value = pd.to_numeric(a["value_raw"], errors="coerce") / (10.0**decimals)
    index = pd.to_numeric(a["index_raw"], errors="coerce") / _RAY
    scaled = value / index
    # Mint credits address_1 (+); Burn and BalanceTransfer's own leg both
    # debit address_1 (-) -- BalanceTransfer's credit to address_2 is a
    # second, separate row below.
    sign = np.where(a["event_type"].to_numpy() == "Mint", 1.0, -1.0)

    leg1 = pd.DataFrame(
        {
            "block_number": a["block_number"].to_numpy(),
            "log_index": a["log_index"].to_numpy(),
            "user": a["address_1"].to_numpy(),
            "reserve": a["reserve"].to_numpy(),
            "scaled_collateral": scaled.to_numpy() * sign,
            "scaled_debt": 0.0,
            "tx_hash": a["tx_hash"].to_numpy(),
        }
    )
    bt = a["event_type"] == "BalanceTransfer"
    leg2 = pd.DataFrame(
        {
            "block_number": a.loc[bt, "block_number"].to_numpy(),
            "log_index": a.loc[bt, "log_index"].to_numpy(),
            "user": a.loc[bt, "address_2"].to_numpy(),
            "reserve": a.loc[bt, "reserve"].to_numpy(),
            "scaled_collateral": scaled[bt].to_numpy(),
            "scaled_debt": 0.0,
            "tx_hash": a.loc[bt, "tx_hash"].to_numpy(),
        }
    )
    return pd.concat([leg1, leg2], ignore_index=True)


def _exact_variable_debt_ledger_rows(
    variable_debt_events: pd.DataFrame, decimals_by_address: dict
) -> pd.DataFrame:
    """Variable-debt ledger rows built directly from `VariableDebtToken`
    `Mint`/`Burn` events (CAS-28 H3) -- same exact-index, no-lookup
    construction as `_exact_atoken_ledger_rows`. `Mint`'s real debtor is its
    *second* indexed address (`onBehalfOf`, not the calling wrapper) --
    verified 5/5 against the already-verified `fix_gateway_onbehalfof.py`
    `Borrow.onBehalfOf` for shared tx hashes (see backfill script
    docstring)."""
    if variable_debt_events.empty:
        return _empty_ledger_rows()
    v = variable_debt_events
    decimals = v["reserve"].map(decimals_by_address).fillna(18)
    value = pd.to_numeric(v["value_raw"], errors="coerce") / (10.0**decimals)
    index = pd.to_numeric(v["index_raw"], errors="coerce") / _RAY
    scaled = value / index
    sign = np.where(v["event_type"].to_numpy() == "Mint", 1.0, -1.0)
    return pd.DataFrame(
        {
            "block_number": v["block_number"].to_numpy(),
            "log_index": v["log_index"].to_numpy(),
            "user": v["user"].to_numpy(),
            "reserve": v["reserve"].to_numpy(),
            "scaled_collateral": 0.0,
            "scaled_debt": scaled.to_numpy() * sign,
            "tx_hash": v["tx_hash"].to_numpy(),
        }
    )


def _exact_token_ledger(
    atoken_events: pd.DataFrame,
    variable_debt_events: pd.DataFrame,
    reserve_table: pd.DataFrame,
) -> pd.DataFrame:
    """Full replacement ledger (CAS-28 H3) for the collateral + variable-debt
    legs, built purely from aToken/variableDebtToken events -- see
    `_exact_atoken_ledger_rows`/`_exact_variable_debt_ledger_rows`. Also
    covers `LiquidationCall`'s collateral seizure and debt repayment for
    free: both fire through these same token events on-chain (confirmed
    against a real liquidation receipt -- see the backfill script's module
    docstring), so no separate LiquidationCall handling is needed here,
    unlike `build_ledger`."""
    decimals_by_address = reserve_table.set_index("address")["decimals"].to_dict()
    parts = [
        _exact_atoken_ledger_rows(atoken_events, decimals_by_address),
        _exact_variable_debt_ledger_rows(variable_debt_events, decimals_by_address),
    ]
    # Drop genuinely-empty parts before concatenating: a freshly-constructed
    # empty frame's string columns default to plain `object` dtype (nothing
    # to infer a type from), and concatenating that with a real, non-empty
    # (pandas-inferred `str`-dtype) part silently downgrades the *combined*
    # column back to `object` -- which then fails a later `merge`/
    # `merge_asof` against any separately-loaded `str`-dtype frame (pandas
    # 3.0's `future.infer_string`). Skipping empty parts avoids ever mixing
    # the two.
    parts = [p for p in parts if not p.empty]
    ledger = pd.concat(parts, ignore_index=True) if parts else _empty_ledger_rows()
    return ledger.sort_values(
        ["block_number", "log_index"], kind="mergesort"
    ).reset_index(drop=True)


def _stable_debt_checkpoints(
    stable_debt_events: pd.DataFrame, decimals_by_address: dict
) -> pd.DataFrame:
    """Per-(user, reserve) stable-debt balance checkpoints (CAS-28 H3) -- one
    row per `StableDebtToken` `Mint`/`Burn` event, giving the exact real
    balance and the position's blended locked rate immediately after that
    event. Aave tracks stable debt as a per-position principal plus a single
    blended `avgStableRate` (re-weighted on every mint), not a shared pool
    index -- unlike collateral/variable debt, this can't be expressed as a
    scaled balance against a shared index, so each checkpoint instead carries
    its own forward-compounding basis (`principal_after`, `avg_rate_after`,
    `block_timestamp`), consumed by `_stable_debt_units` via `merge_asof`.

    The event's own `currentBalance` field is the exact real balance
    *before* this mint/burn's principal change -- Aave has already done the
    interest-accrual math for us, so `principal_after` needs no external
    index lookup, just `currentBalance +/- amount`.

    `tx_hash` (CAS-28 H4-general): same same-transaction-exclusion purpose as
    `_empty_ledger_rows`'s -- see `position_at_log_index`."""
    columns = [
        "user",
        "reserve",
        "block_number",
        "log_index",
        "block_timestamp",
        "principal_after",
        "avg_rate_after",
        "tx_hash",
    ]
    if stable_debt_events.empty:
        return pd.DataFrame(columns=columns)
    s = stable_debt_events
    decimals = s["reserve"].map(decimals_by_address).fillna(18)
    amount = pd.to_numeric(s["amount_raw"], errors="coerce") / (10.0**decimals)
    current_balance = pd.to_numeric(s["current_balance_raw"], errors="coerce") / (
        10.0**decimals
    )
    avg_rate = pd.to_numeric(s["avg_stable_rate_raw"], errors="coerce") / _RAY
    sign = np.where(s["event_type"].to_numpy() == "Mint", 1.0, -1.0)
    principal_after = current_balance.to_numpy() + amount.to_numpy() * sign
    checkpoints = pd.DataFrame(
        {
            "user": s["user"].to_numpy(),
            "reserve": s["reserve"].to_numpy(),
            "block_number": s["block_number"].to_numpy(),
            "log_index": s["log_index"].to_numpy(),
            "block_timestamp": s["block_timestamp"].to_numpy(),
            "principal_after": principal_after,
            "avg_rate_after": avg_rate.to_numpy(),
            "tx_hash": s["tx_hash"].to_numpy(),
        }
    )
    return checkpoints.sort_values(
        ["user", "reserve", "block_number", "log_index"], kind="mergesort"
    ).reset_index(drop=True)


def _stable_debt_only_anchor_rows(
    ledger: pd.DataFrame, stable_debt_checkpoints: pd.DataFrame
) -> pd.DataFrame:
    """Zero-effect ledger rows (CAS-28 H3) for any `(user, reserve)` pair
    that has a stable-debt checkpoint but never appears in `ledger` at all
    (a position that took on stable debt without this engine ever observing
    an aToken/variableDebtToken event for that same reserve). Without this,
    `positions_at`/`positions_at_many`/`position_at_log_index` would never
    discover that `(user, reserve)` pair -- they only iterate pairs found in
    `self.ledger` -- and the position's stable debt would be silently
    dropped rather than added by `_reinflate`.

    Anchored at the block/log_index of that pair's *first* stable-debt
    checkpoint, so the pair correctly doesn't exist for any query before it,
    and correctly appears (with a real, non-zero `debt_units` contributed by
    `_stable_debt_units`, on top of this row's hard-zero scaled legs) for any
    query at or after it."""
    if stable_debt_checkpoints.empty:
        return ledger.iloc[0:0]
    # Set/MultiIndex membership on raw values (not a dtype-strict `.merge`)
    # -- `ledger`'s (user, reserve) columns can be plain-`object`-typed while
    # `stable_debt_checkpoints`'s are parquet/Arrow-string-typed (or vice
    # versa) depending on which construction path built each frame; a
    # `.merge` on those columns raises `MergeError` on the dtype mismatch,
    # but value-level `.isin` doesn't care.
    ledger_pairs = pd.MultiIndex.from_arrays(
        [ledger["user"].to_numpy(), ledger["reserve"].to_numpy()]
    )
    first_checkpoint = stable_debt_checkpoints.groupby(
        ["user", "reserve"], as_index=False
    ).first()  # pre-sorted by (user, reserve, block_number, log_index)
    stable_pairs = pd.MultiIndex.from_arrays(
        [first_checkpoint["user"].to_numpy(), first_checkpoint["reserve"].to_numpy()]
    )
    missing = first_checkpoint[~stable_pairs.isin(ledger_pairs)]
    if missing.empty:
        return ledger.iloc[0:0]
    # `tx_hash=""` (never matches any real trigger's tx_hash): these rows are
    # synthetic zero-effect placeholders, not real transactions, so they must
    # never participate in `position_at_log_index`'s same-tx exclusion --
    # moot anyway since both scaled legs are hard-zero regardless.
    return missing[["user", "reserve", "block_number", "log_index"]].assign(
        scaled_collateral=0.0, scaled_debt=0.0, tx_hash=""
    )


def _stable_debt_units(
    checkpoints: pd.DataFrame | None, keys: pd.DataFrame
) -> np.ndarray:
    """Reinflate stable debt (CAS-28 H3) for each `(user, reserve,
    block_number[, query_timestamp])` key via `merge_asof` against the
    position's own checkpoint history, compounding forward from the
    checkpoint's *locked* `avg_rate_after` (not the pool variable index) when
    `query_timestamp` is given -- mirrors `InterestIndexOracle`'s H5
    forward-compounding, just keyed per-position instead of per-reserve.
    Returns 0.0 for keys with no stable-debt checkpoint (no H3 pull, or the
    position never carried stable debt) -- additive on top of the
    variable-debt term, never a replacement for it.

    `keys`'s row order is preserved regardless of `merge_asof`'s internal
    sort requirement (an explicit `_orig_pos` column survives the sort/merge
    round-trip, avoiding any reliance on pandas' index-preservation
    behavior)."""
    n = len(keys)
    if checkpoints is None or checkpoints.empty or n == 0:
        return np.zeros(n)
    sorted_keys = keys.reset_index(drop=True).assign(_orig_pos=np.arange(n))
    sorted_keys = sorted_keys.sort_values("block_number", kind="mergesort")
    merged = pd.merge_asof(
        sorted_keys,
        # `merge_asof` requires the right side sorted *globally* by `on`
        # (block_number), not merely within each `by` group -- checkpoints
        # is stored sorted by (user, reserve, block_number, log_index) for
        # its other consumer (`_stable_debt_only_anchor_rows`'s
        # `groupby(...).first()`), so re-sort here, matching the same
        # re-sort-immediately-before-merge_asof pattern `positions_at_many`
        # already uses for the ledger.
        checkpoints[
            [
                "user",
                "reserve",
                "block_number",
                "block_timestamp",
                "principal_after",
                "avg_rate_after",
            ]
        ].sort_values("block_number", kind="mergesort"),
        on="block_number",
        by=["user", "reserve"],
        direction="backward",
    )
    principal = merged["principal_after"].fillna(0.0).to_numpy()
    if "query_timestamp" in merged.columns:
        elapsed = (
            (merged["query_timestamp"] - merged["block_timestamp"])
            .dt.total_seconds()
            .fillna(0.0)
            .clip(lower=0.0)
            .to_numpy()
        )
        rate = merged["avg_rate_after"].fillna(0.0).to_numpy()
        contribution = principal * _compounded_interest_array(rate, elapsed)
    else:
        contribution = principal
    result = np.zeros(n)
    result[merged["_orig_pos"].to_numpy()] = contribution
    return result


@lru_cache(maxsize=4)
def _load_interest_index_oracle(
    data_dir: str = "data/raw",
) -> InterestIndexOracle | None:
    """`InterestIndexOracle` for Track E's accrual scaling (CAS-28), or
    `None` if `data/raw/aave_v2_reserve_index/` hasn't been pulled yet --
    same no-op-when-missing convention as every other CAS-28 correction, so
    a checkout without the reserve-index pull still reproduces the
    pre-Track-E (no accrual) balances rather than erroring.

    Cached: the oracle is read-only after construction (only ever queried
    via `index_at`/`index_at_many`) and its backing parquet is multi-million
    rows, expensive enough that reloading it for every `PositionStateEngine`
    instantiation roughly doubled the test suite's runtime before this was
    added."""
    try:
        return InterestIndexOracle(data_dir=data_dir)
    except FileNotFoundError:
        return None


def _scale_ledger_rows(
    ledger: pd.DataFrame, oracle: InterestIndexOracle | None
) -> pd.DataFrame:
    """Convert each ledger row's raw token-unit delta into an index-scaled
    delta -- Aave's own on-chain "scaledBalance" pattern (Track E, CAS-28):
    `scaled = raw / index_at(event_block)`, so that cumulative scaled
    balances can later be reinflated by the index *at query time* to yield
    real, interest-accrued balances (`PositionStateEngine._reinflate`).

    Collateral deltas scale by the `liquidity` index (aToken growth); debt
    deltas scale by the `variable_borrow` index (variable-debt growth) --
    `estimate_interest_accrual_gap.py` found the debt leg is the dominant
    effect (mean 18.4% growth over real accounts' actual holding periods,
    vs collateral's mean 1.2%). Missing coverage (no oracle, or a specific
    reserve/block outside it) falls back to a 1.0 divisor per *row*, not
    per user -- degrading gracefully to the pre-Track-E raw delta for just
    that event, rather than an all-or-nothing gate (see interest_index.py's
    module docstring for why row-level fallback was chosen over per-user).
    """
    if oracle is None or ledger.empty:
        return ledger.assign(
            scaled_collateral=ledger["d_collateral"],
            scaled_debt=ledger["d_debt"],
        )
    liquidity_index = oracle.index_at_many(
        ledger["reserve"], ledger["block_number"], "liquidity"
    ).fillna(1.0)
    variable_index = oracle.index_at_many(
        ledger["reserve"], ledger["block_number"], "variable_borrow"
    ).fillna(1.0)
    return ledger.assign(
        scaled_collateral=ledger["d_collateral"].to_numpy()
        / liquidity_index.to_numpy(),
        scaled_debt=ledger["d_debt"].to_numpy() / variable_index.to_numpy(),
    )


def load_events(
    data_dir: str | Path = "data/raw",
    protocol: str = "aave_v2",
) -> pd.DataFrame:
    """Load + concatenate core + liquidation events for one protocol.

    Sorted by (block_number, log_index) for deterministic replay order.
    """
    data_dir = Path(data_dir)
    paths = sorted(glob.glob(str(data_dir / protocol / "chain=*" / "*.parquet")))
    if not paths:
        raise FileNotFoundError(
            f"No parquet files found for protocol {protocol!r} under {data_dir}"
        )
    df = pd.concat([pd.read_parquet(p) for p in paths], ignore_index=True)
    df = df[df["event_type"].isin(CORE_EVENT_TYPES | LIQUIDATION_EVENT_TYPES)].copy()
    df = df.drop_duplicates(subset=["tx_hash", "log_index"])
    if protocol == "aave_v2":
        df = _apply_onbehalfof_correction(df)
        df = _apply_withdraw_correction(df)
    df = df.sort_values(["block_number", "log_index"], kind="mergesort").reset_index(
        drop=True
    )
    return df


def _units(
    amount_raw: pd.Series, reserve: pd.Series, decimals_by_address: dict
) -> pd.Series:
    decimals = reserve.map(decimals_by_address).fillna(18)
    numeric = pd.to_numeric(amount_raw, errors="coerce").fillna(0.0)
    return numeric / (10.0**decimals)


def build_ledger(events: pd.DataFrame, reserve_table: pd.DataFrame) -> pd.DataFrame:
    """Vectorize the event stream into signed per-(user, reserve) unit deltas.

    One core event -> one ledger row; one liquidation -> two rows (a
    collateral debit on `collateral_asset`, a debt debit on `debt_asset`).
    Pure function of `events`/`reserve_table` -- the Track C aToken-transfer
    correction (global, protocol-wide, independent of whatever `events`
    subset a caller passes in) is applied separately by
    `PositionStateEngine.__post_init__` via `_atoken_transfer_ledger_rows`.
    """
    decimals_by_address = reserve_table.set_index("address")["decimals"].to_dict()
    parts: list[pd.DataFrame] = []

    core = events[events["event_type"].isin(CORE_EVENT_TYPES)]
    if not core.empty:
        core = core.copy()
        core["reserve"] = core["debt_asset"]  # schema quirk: reserve always lands here
        units = _units(core["amount_raw"], core["reserve"], decimals_by_address)
        collateral_sign = (
            core["event_type"].map({"Deposit": 1.0, "Withdraw": -1.0}).fillna(0.0)
        )
        debt_sign = core["event_type"].map({"Borrow": 1.0, "Repay": -1.0}).fillna(0.0)
        core_ledger = pd.DataFrame(
            {
                "block_number": core["block_number"].to_numpy(),
                "log_index": core["log_index"].to_numpy(),
                "user": core["user"].to_numpy(),
                "reserve": core["reserve"].to_numpy(),
                "d_collateral": (units * collateral_sign).to_numpy(),
                "d_debt": (units * debt_sign).to_numpy(),
            }
        )
        parts.append(core_ledger)

    liq = events[events["event_type"].isin(LIQUIDATION_EVENT_TYPES)]
    if not liq.empty:
        liq = liq.copy()
        collateral_units = _units(
            liq["collateral_seized_raw"], liq["collateral_asset"], decimals_by_address
        )
        debt_units = _units(liq["amount_raw"], liq["debt_asset"], decimals_by_address)

        collateral_debit = pd.DataFrame(
            {
                "block_number": liq["block_number"].to_numpy(),
                "log_index": liq["log_index"].to_numpy(),
                "user": liq["user"].to_numpy(),
                "reserve": liq["collateral_asset"].to_numpy(),
                "d_collateral": (-collateral_units).to_numpy(),
                "d_debt": 0.0,
            }
        )
        debt_debit = pd.DataFrame(
            {
                "block_number": liq["block_number"].to_numpy(),
                "log_index": liq["log_index"].to_numpy(),
                "user": liq["user"].to_numpy(),
                "reserve": liq["debt_asset"].to_numpy(),
                "d_collateral": 0.0,
                "d_debt": (-debt_units).to_numpy(),
            }
        )
        parts.append(collateral_debit)
        parts.append(debt_debit)

    if not parts:
        return pd.DataFrame(columns=_LEDGER_COLUMNS)

    ledger = pd.concat(parts, ignore_index=True)[_LEDGER_COLUMNS]
    return ledger.sort_values(
        ["block_number", "log_index"], kind="mergesort"
    ).reset_index(drop=True)


def _atoken_transfer_ledger_rows(
    events: pd.DataFrame, reserve_table: pd.DataFrame
) -> pd.DataFrame:
    """Synthetic ledger rows (Track C, CAS-28) for "naked" aToken `Transfer`
    events that move collateral directly between two live accounts, bypassing
    every `LendingPool` event `build_ledger` otherwise replays -- e.g. Aave's
    own Uniswap/ParaSwap repay-and-collateral-swap adapters pull a user's
    aTokens via `transferFrom` directly against the aToken contract rather
    than calling `LendingPool.withdraw`. One `Transfer` -> two rows: a
    collateral debit on `from_user`, a collateral credit on `to_user`, both on
    the transfer's underlying reserve.

    Excludes any transfer sharing a tx_hash with a `LiquidationCall` in
    `events` -- a liquidator opting to `receiveAToken` seizes collateral via
    this exact same mechanism inside the `LiquidationCall` transaction
    itself, and `build_ledger`'s `LiquidationCall` branch already accounts
    for that seizure (see module docstring); applying it again here would
    double-debit the borrower for their own liquidation.

    Deliberately kept out of `build_ledger` itself (which stays a pure
    function of its `events`/`reserve_table` arguments) and called instead
    from `PositionStateEngine.__post_init__`, since this correction table is
    global/protocol-wide and independent of whatever `events` a caller
    passes in -- mirrors Track B's `_load_collateral_toggle_events` split."""
    atoken_transfers = _load_atoken_transfer_corrections()
    if atoken_transfers.empty:
        return pd.DataFrame(columns=_LEDGER_COLUMNS)

    if "tx_hash" in events.columns:
        liquidation_tx_hashes = set(
            events.loc[events["event_type"].isin(LIQUIDATION_EVENT_TYPES), "tx_hash"]
        )
        atoken_transfers = atoken_transfers[
            ~atoken_transfers["tx_hash"].isin(liquidation_tx_hashes)
        ]
    if atoken_transfers.empty:
        return pd.DataFrame(columns=_LEDGER_COLUMNS)

    decimals_by_address = reserve_table.set_index("address")["decimals"].to_dict()
    units = _units(
        atoken_transfers["value_raw"], atoken_transfers["reserve"], decimals_by_address
    )
    transfer_debit = pd.DataFrame(
        {
            "block_number": atoken_transfers["block_number"].to_numpy(),
            "log_index": atoken_transfers["log_index"].to_numpy(),
            "user": atoken_transfers["from_user"].to_numpy(),
            "reserve": atoken_transfers["reserve"].to_numpy(),
            "d_collateral": (-units).to_numpy(),
            "d_debt": 0.0,
        }
    )
    transfer_credit = pd.DataFrame(
        {
            "block_number": atoken_transfers["block_number"].to_numpy(),
            "log_index": atoken_transfers["log_index"].to_numpy(),
            "user": atoken_transfers["to_user"].to_numpy(),
            "reserve": atoken_transfers["reserve"].to_numpy(),
            "d_collateral": units.to_numpy(),
            "d_debt": 0.0,
        }
    )
    return pd.concat([transfer_debit, transfer_credit], ignore_index=True)[
        _LEDGER_COLUMNS
    ]


@dataclass
class PositionStateEngine:
    """Replays a sorted event stream into per-account balances at any block."""

    events: pd.DataFrame
    reserve_table: pd.DataFrame = field(default_factory=reserves_module.reserve_table)
    ledger: pd.DataFrame = field(init=False, repr=False)
    collateral_toggle: pd.DataFrame = field(init=False, repr=False)
    interest_index: InterestIndexOracle | None = field(init=False, repr=False)
    stable_debt_checkpoints: pd.DataFrame | None = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self.interest_index = _load_interest_index_oracle()
        token_ledger = _load_token_ledger_events()
        if token_ledger is not None:
            # CAS-28 H3: exact token-level ledger supersedes the
            # LendingPool-event replay + corrections below entirely for the
            # collateral/variable-debt legs (see `_exact_token_ledger`'s
            # docstring for why LiquidationCall needs no special handling
            # here); stable debt gets its own locked-rate checkpoint table,
            # consumed additively by `_reinflate`/`positions_at_many`.
            atoken_events, variable_debt_events, stable_debt_events = token_ledger
            self.ledger = _exact_token_ledger(
                atoken_events, variable_debt_events, self.reserve_table
            )
            decimals_by_address = self.reserve_table.set_index("address")[
                "decimals"
            ].to_dict()
            self.stable_debt_checkpoints = _stable_debt_checkpoints(
                stable_debt_events, decimals_by_address
            )
            anchors = _stable_debt_only_anchor_rows(
                self.ledger, self.stable_debt_checkpoints
            )
            if not anchors.empty:
                # `self.ledger` may itself be genuinely empty here (e.g. a
                # position with *only* stable debt, no aToken/variableDebt
                # event at all) -- concatenating an empty `object`-dtype
                # frame onto a non-empty `str`-dtype one downgrades the
                # combined dtype and breaks later merges (see
                # `_exact_token_ledger`'s comment), so skip the concat
                # entirely when there's nothing to concatenate onto.
                self.ledger = (
                    anchors
                    if self.ledger.empty
                    else pd.concat(
                        [self.ledger, anchors], ignore_index=True
                    ).sort_values(["block_number", "log_index"], kind="mergesort")
                )
                self.ledger = self.ledger.reset_index(drop=True)
        else:
            self.ledger = build_ledger(self.events, self.reserve_table)
            atoken_rows = _atoken_transfer_ledger_rows(self.events, self.reserve_table)
            if not atoken_rows.empty:
                self.ledger = pd.concat(
                    [self.ledger, atoken_rows], ignore_index=True
                ).sort_values(["block_number", "log_index"], kind="mergesort")
                self.ledger = self.ledger.reset_index(drop=True)
            self.ledger = _scale_ledger_rows(self.ledger, self.interest_index)
            self.stable_debt_checkpoints = None
        self.collateral_toggle = _load_collateral_toggle_events()

    @classmethod
    def from_data_dir(
        cls, data_dir: str | Path = "data/raw", protocol: str = "aave_v2"
    ) -> "PositionStateEngine":
        events = load_events(data_dir=data_dir, protocol=protocol)
        return cls(events=events)

    def _attach_collateral_enabled(
        self, positions: pd.DataFrame, block_number: int
    ) -> pd.DataFrame:
        """Join the per-(user, reserve) collateral-eligibility flag as of
        `block_number` -- the latest `ReserveUsedAsCollateralEnabled`/
        `Disabled` event at or before it (Track B, CAS-28). Defaults to
        `True` when the corrections table hasn't been pulled, or a (user,
        reserve) pair has no toggle event yet -- both cases where the prior
        "every deposit is collateral-eligible" assumption is the only
        information available."""
        if self.collateral_toggle.empty:
            return positions.assign(collateral_enabled=True)
        sub = self.collateral_toggle[
            self.collateral_toggle["block_number"] <= block_number
        ]
        if sub.empty:
            return positions.assign(collateral_enabled=True)
        latest = sub.groupby(["user", "reserve"], as_index=False).last()[
            ["user", "reserve", "enabled"]
        ]
        merged = positions.merge(latest, on=["user", "reserve"], how="left")
        merged["collateral_enabled"] = merged["enabled"].fillna(True)
        return merged.drop(columns=["enabled"])

    def _reinflate(
        self,
        agg: pd.DataFrame,
        block_number: int,
        query_timestamp: pd.Timestamp | None = None,
        log_index_cutoff: int | None = None,
    ) -> pd.DataFrame:
        """Multiply scaled (index-normalized) balances back into real
        token-unit terms as of `block_number` -- the query-time half of
        Track E's accrual scaling (CAS-28; see `_scale_ledger_rows` for the
        event-time half). Falls back to a 1.0 multiplier (no accrual) when
        the oracle is unavailable or a given reserve/block isn't covered,
        the same no-op convention as every other CAS-28 correction.

        `query_timestamp` (CAS-28 H5): forward-compounds the index from its
        last on-chain write to this exact moment (see
        `interest_index.InterestIndexOracle`); omit to reinflate by the
        stored index as-of `block_number` only (pre-H5 behavior, still used
        by every caller that doesn't have a specific trigger moment).

        CAS-28 H3: also adds any stable debt on top of the variable-debt
        term above (`_stable_debt_units`) -- independent of `interest_index`
        (stable debt compounds at its own locked rate, not the pool index),
        so it's applied even when the reserve-index oracle is unavailable.

        `log_index_cutoff` (CAS-28 H4-general bugfix): `_stable_debt_units`
        resolves each key by `merge_asof` on `block_number` alone, with no
        log_index granularity -- fine for `positions_at`/`positions_at_many`
        (always querying a *whole* block boundary, e.g. `block_number - 1`),
        but wrong for `position_at_log_index`, which passes the trigger's
        OWN `block_number` and needs anything at-or-after its cutoff
        `log_index` within that same block excluded (most importantly, the
        triggering liquidation's own stable-debt repayment). Only
        `position_at_log_index` passes this; `None` elsewhere reproduces the
        pre-existing block-level-only behavior exactly."""
        agg = agg.rename(
            columns={
                "scaled_collateral": "collateral_units",
                "scaled_debt": "debt_units",
            }
        )
        if agg.empty:
            return agg
        if self.interest_index is not None:
            timestamps = (
                pd.Series(query_timestamp, index=agg.index)
                if query_timestamp is not None
                else None
            )
            liquidity = self.interest_index.index_at_many(
                agg["reserve"],
                pd.Series(block_number, index=agg.index),
                "liquidity",
                query_timestamps=timestamps,
            ).fillna(1.0)
            variable = self.interest_index.index_at_many(
                agg["reserve"],
                pd.Series(block_number, index=agg.index),
                "variable_borrow",
                query_timestamps=timestamps,
            ).fillna(1.0)
            agg["collateral_units"] = (
                agg["collateral_units"].to_numpy() * liquidity.to_numpy()
            )
            agg["debt_units"] = agg["debt_units"].to_numpy() * variable.to_numpy()
        if (
            self.stable_debt_checkpoints is not None
            and not self.stable_debt_checkpoints.empty
        ):
            checkpoints = self.stable_debt_checkpoints
            if log_index_cutoff is not None:
                exclude = (checkpoints["block_number"] == block_number) & (
                    checkpoints["log_index"] >= log_index_cutoff
                )
                if exclude.any():
                    checkpoints = checkpoints[~exclude]
            keys = agg[["user", "reserve"]].assign(block_number=block_number)
            if query_timestamp is not None:
                keys = keys.assign(query_timestamp=query_timestamp)
            agg["debt_units"] = agg["debt_units"].to_numpy() + _stable_debt_units(
                checkpoints, keys
            )
        return agg

    def positions_at(
        self, block_number: int, query_timestamp: pd.Timestamp | None = None
    ) -> pd.DataFrame:
        """Cumulative (user, reserve) balances as of `block_number`, inclusive.

        Drops (user, reserve) rows that have netted to ~0 in both legs.
        `query_timestamp` (CAS-28 H5): see `_reinflate`.
        """
        sub = self.ledger[self.ledger["block_number"] <= block_number]
        if sub.empty:
            return pd.DataFrame(
                columns=[
                    "user",
                    "reserve",
                    "collateral_units",
                    "debt_units",
                    "collateral_enabled",
                ]
            )
        agg = sub.groupby(["user", "reserve"], as_index=False)[
            ["scaled_collateral", "scaled_debt"]
        ].sum()
        agg = self._reinflate(agg, block_number, query_timestamp)
        agg = agg[
            (agg["collateral_units"].abs() > _EPS) | (agg["debt_units"].abs() > _EPS)
        ]
        agg = self._attach_collateral_enabled(agg, block_number)
        return agg.reset_index(drop=True)

    def position_at_log_index(
        self,
        user: str,
        block_number: int,
        log_index: int,
        tx_hash: str | None = None,
        after_log_index: int | None = None,
        query_timestamp: pd.Timestamp | None = None,
    ) -> pd.DataFrame:
        """Precise cumulative balances for one user strictly *before*
        `(block_number, log_index)` -- i.e. including any earlier event in
        the SAME block (CAS-28 H4), unlike `positions_at`/`positions_at_many`,
        which can only cut at a whole `block_number` boundary.

        Needed for same-block liquidation cascades: two `LiquidationCall`
        events for the same user in one block are not simultaneous (EVM
        execution is sequential even within one block, and even within one
        tx), so the second liquidation's true pre-state includes the first's
        seizure/repay. `positions_at_many` queried at `block_number - 1` for
        both would incorrectly give them identical pre-states, silently
        treating the second as never happening (see `t2_gate.py`). CAS-28
        H4-general (2026-07-22) widened this beyond the cascade case to any
        trigger with same-block-earlier ledger activity for the same user.

        `tx_hash` -- **required to get the trigger's OWN transaction right**
        (CAS-28 H4-general bugfix): a liquidation's own internal token
        events (aToken `Burn`/`BalanceTransfer`, debt-token `Burn`) can have
        a LOWER `log_index` than the outer `LiquidationCall` event itself --
        confirmed on real data (a variableDebtToken `Burn` at log_index 47
        for a `LiquidationCall` at log_index 56, same tx). Cutting at
        `log_index < log_index` alone would then wrongly include that
        liquidation's OWN seizure/repay as its own "pre-state". When
        `tx_hash` is given and `self.ledger`/`self.stable_debt_checkpoints`
        carry a `tx_hash` column (H3 path only -- see `_empty_ledger_rows`),
        the cutoff widens to the MIN log_index among this user's own
        same-block, same-`tx_hash` rows above `after_log_index` (if lower
        than `log_index`), excluding the trigger's own transaction rather
        than just its outer event. Omit (or on the pre-H3 fallback path,
        which has no such rows/bug -- `build_ledger` derives LiquidationCall's
        ledger rows directly from that event, so they always land at exactly
        its own `log_index`) to reproduce the pre-bugfix exact-`log_index`
        cutoff.

        `after_log_index` -- **required when >1 `LiquidationCall` for this
        user shares this SAME `tx_hash`** (confirmed real: 174 real
        `(tx_hash, user)` pairs, e.g. one batched tx liquidating two
        different debt reserves of the same position back to back --
        sequential calls within one tx still execute one after another, each
        with its own complete burn/repay effects before the next begins). Set
        to the *previous* same-user, same-`tx_hash` trigger's own `log_index`
        (`None` if this is the first/only such trigger in the tx) so the
        same-`tx_hash` widening above only searches log_index > that floor --
        otherwise it would sweep in and wrongly exclude the *earlier*
        trigger's real, legitimate effects too, not just this one's own.

        Only called for the (still small, but no longer cascade-only) subset
        of triggers with same-block-earlier activity -- O(ledger size) per
        call is fine at that scale; the O((keys x reserves) log n) batched
        `positions_at_many` remains the path for the majority with none.
        """
        user = user.lower()
        ledger = self.ledger
        cutoff_log_index = log_index
        if tx_hash is not None and "tx_hash" in ledger.columns:
            same_tx = ledger[
                (ledger["user"] == user)
                & (ledger["block_number"] == block_number)
                & (ledger["tx_hash"] == tx_hash)
            ]
            if after_log_index is not None:
                same_tx = same_tx[same_tx["log_index"] > after_log_index]
            if not same_tx.empty:
                cutoff_log_index = min(
                    cutoff_log_index, int(same_tx["log_index"].min())
                )
            checkpoints = self.stable_debt_checkpoints
            if checkpoints is not None and not checkpoints.empty:
                same_tx_stable = checkpoints[
                    (checkpoints["user"] == user)
                    & (checkpoints["block_number"] == block_number)
                    & (checkpoints["tx_hash"] == tx_hash)
                ]
                if after_log_index is not None:
                    same_tx_stable = same_tx_stable[
                        same_tx_stable["log_index"] > after_log_index
                    ]
                if not same_tx_stable.empty:
                    cutoff_log_index = min(
                        cutoff_log_index, int(same_tx_stable["log_index"].min())
                    )
        sub = ledger[
            (ledger["user"] == user)
            & (
                (ledger["block_number"] < block_number)
                | (
                    (ledger["block_number"] == block_number)
                    & (ledger["log_index"] < cutoff_log_index)
                )
            )
        ]
        if sub.empty:
            return pd.DataFrame(
                columns=[
                    "user",
                    "reserve",
                    "collateral_units",
                    "debt_units",
                    "collateral_enabled",
                ]
            )
        agg = sub.groupby("reserve", as_index=False)[
            ["scaled_collateral", "scaled_debt"]
        ].sum()
        agg.insert(0, "user", user)
        agg = self._reinflate(
            agg, block_number, query_timestamp, log_index_cutoff=cutoff_log_index
        )
        agg = agg[
            (agg["collateral_units"].abs() > _EPS) | (agg["debt_units"].abs() > _EPS)
        ]
        agg = self._attach_collateral_enabled(agg, block_number)
        return agg.reset_index(drop=True)

    def same_block_earlier_tx(self, keys: pd.DataFrame) -> np.ndarray:
        """For each `(user, block_number, log_index, tx_hash)` row in `keys`,
        True if that user has ledger/stable-debt activity from a
        **different** transaction earlier in the same block (CAS-28
        H4-general) -- i.e. `positions_at_many`'s `block_number - 1` batched
        cut would miss real same-block-earlier state for this trigger, and
        the precise `position_at_log_index` should be used instead.

        Generalizes Lever 7 (H4a)'s cascade check ("does this user have
        another `LiquidationCall` in this block") to ANY earlier same-block
        action by the same user -- a Withdraw, a Borrow, or another
        liquidation in a separate tx. Motivated by CAS-28 H7's archive-node
        spot-check: 38.3% of a real "unexplained"-mismatch sample matched
        Aave's own live contract at the *same* `block_number - 1` cutoff this
        engine uses, meaning something earlier in the trigger's own block --
        invisible to a whole-block cut -- is what actually changed the
        verdict.

        **Does NOT subsume the cascade check -- callers must still OR this
        with it.** Deliberately excludes same-`tx_hash` activity (it can't
        tell "an earlier trigger's own effects, sharing this tx" apart from
        "this trigger's own effects", and get the latter wrong -- see
        `position_at_log_index`'s `after_log_index`), but 174 real
        `(tx_hash, user)` pairs have >1 `LiquidationCall` batched in one tx
        (e.g. liquidating two debt reserves of the same position back to
        back) -- that same-tx cascade case is only caught by comparing
        against other *triggers* directly (`t2_gate.py`'s `cascade_size`
        check), not this ledger-activity scan.

        Restricted to users appearing in `keys` before grouping (mirrors
        `positions_at_many`'s `touched_users` pattern) -- the full ledger is
        multi-million-row, but the liquidated-user subset is a small
        fraction of it.

        Always all-`False` when `self.ledger` has no `tx_hash` column (the
        pre-H3 fallback path -- see `_empty_ledger_rows`): that path's
        whole-block cuts are already exact (no separate token-level events
        with independent log_index), so there's nothing to gain from the
        precise path there.
        """
        n = len(keys)
        if "tx_hash" not in self.ledger.columns:
            return np.zeros(n, dtype=bool)

        touched_users = keys["user"].unique()
        sources = [
            self.ledger.loc[
                self.ledger["user"].isin(touched_users),
                ["user", "block_number", "log_index", "tx_hash"],
            ]
        ]
        checkpoints = self.stable_debt_checkpoints
        if checkpoints is not None and not checkpoints.empty:
            sources.append(
                checkpoints.loc[
                    checkpoints["user"].isin(touched_users),
                    ["user", "block_number", "log_index", "tx_hash"],
                ]
            )
        activity = pd.concat(sources, ignore_index=True)
        if activity.empty:
            return np.zeros(n, dtype=bool)
        activity = activity.groupby(
            ["user", "block_number", "tx_hash"], as_index=False
        )[["log_index"]].min()

        query = keys[["user", "block_number", "log_index", "tx_hash"]].reset_index(
            drop=True
        )
        query = query.assign(_row=np.arange(n))
        merged = query.merge(
            activity.rename(
                columns={"log_index": "other_log_index", "tx_hash": "other_tx_hash"}
            ),
            on=["user", "block_number"],
            how="inner",
        )
        if merged.empty:
            return np.zeros(n, dtype=bool)
        hit = merged[
            (merged["other_tx_hash"] != merged["tx_hash"])
            & (merged["other_log_index"] < merged["log_index"])
        ]
        result = np.zeros(n, dtype=bool)
        if not hit.empty:
            result[hit["_row"].unique()] = True
        return result

    def account_snapshot(self, user: str, block_number: int) -> pd.DataFrame:
        positions = self.positions_at(block_number)
        return positions[positions["user"] == user.lower()].reset_index(drop=True)

    def health_factor_at(
        self,
        user: str,
        block_number: int,
        price_oracle: PriceOracle,
        timestamp: pd.Timestamp,
    ) -> HealthFactorResult:
        position = self.account_snapshot(user, block_number)
        reserves_involved = position["reserve"].unique().tolist()
        prices = price_oracle.prices_at(reserves_involved, timestamp)
        return compute_health_factor(position, prices, self.reserve_table)

    def positions_at_many(self, keys: pd.DataFrame) -> pd.DataFrame:
        """Batch equivalent of `positions_at` for many (user, block_number)
        pairs at once. `keys` has columns `user`, `block_number`, and
        optionally `query_timestamp` (CAS-28 H5) -- if present, forward-
        compounds the interest index from its last on-chain write to that
        exact per-row moment (see `_reinflate`) instead of using the value
        stored as of `block_number` only.

        Naively calling `positions_at` once per key is O(ledger size) per
        call; for tens of thousands of keys against a multi-million-row
        ledger that's far too slow. This instead computes cumulative
        per-(user, reserve) balances once and looks up each key via a single
        grouped `merge_asof`, which is O((keys x reserves per user) log n).

        Returns long-form rows: user, block_number, reserve,
        collateral_units, debt_units -- one row per reserve the user had
        ever touched as of that block (0-valued rows included; callers
        filter as needed).
        """
        ledger = self.ledger.sort_values(
            ["user", "reserve", "block_number", "log_index"], kind="mergesort"
        ).copy()
        grouped = ledger.groupby(["user", "reserve"], sort=False)
        ledger["scaled_collateral_cum"] = grouped["scaled_collateral"].cumsum()
        ledger["scaled_debt_cum"] = grouped["scaled_debt"].cumsum()

        touched_users = keys["user"].unique()
        pairs = ledger[ledger["user"].isin(touched_users)][
            ["user", "reserve"]
        ].drop_duplicates()
        queries = keys.merge(pairs, on="user", how="left").dropna(subset=["reserve"])

        merged = pd.merge_asof(
            queries.sort_values("block_number", kind="mergesort"),
            ledger[
                [
                    "user",
                    "reserve",
                    "block_number",
                    "scaled_collateral_cum",
                    "scaled_debt_cum",
                ]
            ].sort_values("block_number", kind="mergesort"),
            on="block_number",
            by=["user", "reserve"],
            direction="backward",
        )
        merged[["scaled_collateral_cum", "scaled_debt_cum"]] = merged[
            ["scaled_collateral_cum", "scaled_debt_cum"]
        ].fillna(0.0)
        merged = merged.rename(
            columns={
                "scaled_collateral_cum": "collateral_units",
                "scaled_debt_cum": "debt_units",
            }
        )
        # Reinflate the scaled cumulative balance by the index *at the query
        # block* (merge_asof preserves the left/`queries` frame's own
        # `block_number` here, not the matched ledger row's) -- the
        # query-time half of Track E's accrual scaling (CAS-28), same
        # per-row 1.0 fallback as `_reinflate`.
        if self.interest_index is not None and not merged.empty:
            query_timestamps = (
                merged["query_timestamp"]
                if "query_timestamp" in merged.columns
                else None
            )
            liquidity = self.interest_index.index_at_many(
                merged["reserve"],
                merged["block_number"],
                "liquidity",
                query_timestamps=query_timestamps,
            ).fillna(1.0)
            variable = self.interest_index.index_at_many(
                merged["reserve"],
                merged["block_number"],
                "variable_borrow",
                query_timestamps=query_timestamps,
            ).fillna(1.0)
            merged["collateral_units"] = (
                merged["collateral_units"].to_numpy() * liquidity.to_numpy()
            )
            merged["debt_units"] = merged["debt_units"].to_numpy() * variable.to_numpy()

        # CAS-28 H3: add stable debt on top of the variable-debt term above
        # -- independent of `interest_index` (see `_reinflate`), so this
        # runs even when the reserve-index oracle is unavailable.
        if (
            self.stable_debt_checkpoints is not None
            and not self.stable_debt_checkpoints.empty
            and not merged.empty
        ):
            stable_keys_columns = ["user", "reserve", "block_number"]
            if "query_timestamp" in merged.columns:
                stable_keys_columns.append("query_timestamp")
            merged["debt_units"] = merged["debt_units"].to_numpy() + _stable_debt_units(
                self.stable_debt_checkpoints, merged[stable_keys_columns]
            )

        # `merged` is still sorted ascending by block_number here (merge_asof
        # preserves the left frame's row order, and `queries` was passed in
        # pre-sorted) -- safe to chain a second merge_asof for the Track B
        # collateral-eligibility flag without re-sorting.
        if self.collateral_toggle.empty:
            merged["collateral_enabled"] = True
        else:
            merged = pd.merge_asof(
                merged,
                self.collateral_toggle[
                    ["user", "reserve", "block_number", "enabled"]
                ].sort_values("block_number", kind="mergesort"),
                on="block_number",
                by=["user", "reserve"],
                direction="backward",
            )
            merged["collateral_enabled"] = merged["enabled"].fillna(True)
            merged = merged.drop(columns=["enabled"])
        return merged

    def whale_positions(
        self,
        block_number: int,
        price_oracle: PriceOracle,
        timestamp: pd.Timestamp,
        top_n: int = 500,
    ) -> pd.DataFrame:
        """Rank accounts by total USD collateral value at `block_number`.

        Feeds CAS-47's "whale-position tracking for graph nodes" subtask —
        the contagion graph (CAS-23) models the top ~500 whale positions
        individually rather than only in market x asset x HF-band buckets.
        """
        positions = self.positions_at(block_number)
        if positions.empty:
            return pd.DataFrame(columns=["user", "collateral_usd", "debt_usd"])

        all_reserves = positions["reserve"].unique().tolist()
        prices = price_oracle.prices_at(all_reserves, timestamp)
        price_series = positions["reserve"].map(prices)

        positions = positions.assign(
            collateral_usd=positions["collateral_units"].clip(lower=0) * price_series,
            debt_usd=positions["debt_units"].clip(lower=0) * price_series,
        )
        by_user = positions.groupby("user", as_index=False)[
            ["collateral_usd", "debt_usd"]
        ].sum(min_count=1)
        by_user = by_user.sort_values(
            "collateral_usd", ascending=False, na_position="last"
        )
        return by_user.head(top_n).reset_index(drop=True)
